version: '3'
services:
  web:
    build:
      context: ./server/.
      dockerfile: Dockerfile.local
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  chat:
    build:
      context: ./chat/.
      dockerfile: Dockerfile.local 
    volumes:
      - ./chat:/app
    ports:
      - "3000:3000"
