# Use an official Python runtime as a base image
FROM python:3.8-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable for the Flask app
ENV FLASK_APP=app.py

CMD ["sh", "-c", "pip install -r requirements.txt && flask run --host=0.0.0.0"]